#!/bin/bash

if [[ $# -eq 0 || $# -gt 2 ]]; then
    echo "Usage: fig PATTERN [CHOICE]";
else
    files=( `find . | grep -E -i $1`)

    num_ele=${#files[@]}

    if (($num_ele == 0)); then
        echo "No match found."
    elif (($num_ele == 1)); then
        $EDITOR ${files[0]}
    else
        echo "Files:"
        for ((i=0;i<$num_ele;i++)); do
            echo $(($i+1))". " ${files[${i}]}
        done

        echo "Select file: "
        read input

        if echo $input | grep -E -q '^[0-9]+$' 2>/dev/null
        then
            if [[ $input -gt 0 && $input -le $num_ele ]]; then
                $EDITOR ${files[$(($input-1))]}
            else
                echo "Out of range"
            fi
        else
            echo "Not a choice"
        fi
            
    fi
fi
